### ISSUE TITLE
ROCK Pi wifi/ble issues resolved

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/helium-miner-software#402]
Convo: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1647602709503159

Main issue: https://github.com/radxa/meta-radxa/issues/7

**Comment by marvinmarnold** [comment]
@MuratUrsavas could you add details here or point to an existing issue?

**Comment by MuratUrsavas** [comment]
Added the main Radxa repo issue in the first comment. I was able to reproduce the wifi disconnection problem @KevinWassermann94 mentioned and it is pretty serious compared to AP6212's.

**Comment by MuratUrsavas** [comment]
It gets solved with the driver update. The disconnection problem has gone. The WiFi stays up even with stress tests. iperf retrial count dropped from a few hundreds to 1-6 retries. The WiFi connection stays alive and the device works as expected.

We need to make sure Balena OS includes the [latest brcmfmac driver](https://community.infineon.com/t5/Wi-Fi-Bluetooth-for-Linux/Cypress-Linux-WiFi-Driver-Release-FMAC-2021-10-20/td-p/322639).

Following the progress in the Radxa repository issue.

**Comment by MuratUrsavas** [comment]
Unfortunately the problem has appeared in a long running test. The driver has improved the situation but not solved completely. This needs further investigation and I'll be in contact with Infineon (Cypress) for this.

**Comment by pritamghanghas** [comment]
I couldn't follow the conversation properly. What is this result about.
brcmfmac driver with debian image?

**Comment by MuratUrsavas** [comment]
@pritamghanghas Yes, it's official Debian image of Radxa. If you can take a look at the main issue in Radxa repo, you can find further information about the tests, results and environment.

**Comment by MuratUrsavas** [comment]
The latest update from Infineon/Cypress solves the problem. But the driver and firmware have to be updated together. The original driver in Balena and the latest firmware are incompatible and causes module failure at startup.

I'll be in touch with Balena after my account would get connected to premium support.

**Comment by shawaj** [comment]
Issues from Balena repo for reference
https://github.com/balena-os/balena-rockpi/issues/48
https://github.com/balena-os/balena-rockpi/issues/49

**Comment by MuratUrsavas** [comment]
I've verified that latest driver and firmware combo is fixing the problem on AW-NB197SM and works for AP6212, too.

Will be following Balena closely to get the updated release.

**Comment by shawaj** [comment]
awesome - nice work @MuratUrsavas

**Comment by SHJ234** [comment]
Very nice ! How do we know when the update is pushed to the rock pi's? :)

**Comment by MuratUrsavas** [comment]
I've turned off power saving and tested again. Didn't see any noticeable change. Then turned on power saving, and the ping times sky rocketed. So we can assume that power saving is disabled by default.

It doesn't effect the iperf bandwidth test results, tho. The power saving is all about latency.

**Comment by shawaj** [comment]
> Very nice ! How do we know when the update is pushed to the rock pi's? :)

It will be probably be next week. But it will happen automatically. Just leave your unit plugged into Ethernet

**Comment by SHJ234** [comment]
> > Very nice ! How do we know when the update is pushed to the rock pi's? :)
> 
> It will be probably be next week. But it will happen automatically. Just leave your unit plugged into Ethernet

Thank you for your reply. Will this wifi fix also change the device Firmware version in the web interface? I am in a situation where the location i will be placing a miner only has WIFI access. So i need to know beforehand that it is updated with wifi fix.

Will this be posted in changelog in master in github. e.g Wifi and BLE issue fixed?

Sorry if these are self explained questions, i am not very used to github.

**Comment by shawaj** [comment]
@SHJ234 it will not show that no as it's independent of the device software.

However, if you let me know the Mac address and frequency of your unit then I can check and make sure it's updated for you

**Comment by MuratUrsavas** [comment]
The problem has been fixed with the latest Balena OS ESR update. The release has been merged in NebraLtd/hotspot-production-images repo.

I've updated the only online testnet device manually (@vpetersson's)

Not closing the issue since I'm tracking the progress on non-ESR Balena OS release.

**Comment by shawaj** [comment]
@MuratUrsavas I think we can close this as we don't use non-ESR releases

And I've already started updating all testnet and production devices to the new release

**Comment by MuratUrsavas** [comment]
Fair enough.

**Comment by gfelisberto** [comment]
I think this is still not solved. https://www.reddit.com/r/HeliumNetwork/comments/u3dpki/nebra_disconnects_from_network/

**Comment by SHJ234** [comment]
please look into the Wi-Fi issue. It seems like it is not yet solved.

https://www.reddit.com/r/HeliumNetwork/comments/u46x3v/rock_pi_miner_4_wifi_doesnt_work/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by MuratUrsavas** [comment]
It has been verified on all hardware variants, but particular setups may have other kind of problems. 

We just need everyone to reach our support to inform us about the issues they have. We'll be tracking them for a solution.

**Comment by MuratUrsavas** [comment]
@SHJ234 most of the problems are due to outdated base OS software. They're fixed if reached to our support.
